
export const list = [
    {
      id: 1,
      cover: "../images/list/p-1.png",
      name: "France Tour with Switzerland",
      location: "Explore Paris, Geneva and Mt. Tetlis",
      category: "Group Tour",
      price: "200000",
      type: "7 Nights/ 8 Days",
    },
    {
      id: 2,
      cover: "../images/list/p-2.png",
      name: "United Kingdom Tour",
      location: "Explore the heart of Europe in London",
      category: "Customized Tour",
      price: "175000",
      type: "5 Nights/ 6 Days",
    },
    {
      id: 3,
      cover: "../images/list/p-7.png",
      name: "The Heritage Europe",
      location: "Explore the magestic city of Athens and Rome",
      category: "Group Tour",
      price: "$5,860",
      type: "9 Nights / 10 Days",
    },
    {
      id: 4,
      cover: "../images/list/p-4.png",
      name: "Portugese Dreamland",
      location: "Land of cultures and mythology in Porto",
      category: "Cutomized Tour",
      price: "$7,540",
      type: "4 Nights / 5 Days",
    },
    {
      id: 5,
      cover: "../images/list/p-5.png",
      name: "Legends of Africa",
      location: "Come and witness the wonders of South Africa",
      category: "group Tour",
      price: "$4,850",
      type: "10 Days / 11 Nights",
    },
    {
      id: 6,
      cover: "../images/list/p-6.png",
      name: "Middleast Journey",
      location: "Witness the land of Pharaoh- Egypt and Cairo",
      category: "Customized Tour",
      price: "$2,742",
      type: "8 Days / 9 Nights",
    },
  ]
  export const location = [
    {
      id: 1,
      name: "New Orleans, Louisiana",
      Villas: "12 Villas",
      Apartments: "10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-1.png",
    },
    {
      id: 2,
      name: "Jerrsy, United State",
      Villas: "12 Villas",
      Apartments: "10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-2.png",
    },
    {
      id: 3,
      name: "Liverpool, London",
      Villas: "12 Villas",
      Apartments: " 10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-3.png",
    },
    {
      id: 4,
      name: "NewYork, United States",
      Villas: "12 Villas",
      Apartments: " 10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-4.png",
    },
    {
      id: 5,
      name: "Montreal, Canada",
      Villas: "12 Villas",
      Apartments: " 10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-5.png",
    },
    {
      id: 6,
      name: "California, USA",
      Villas: "12 Villas",
      Apartments: " 10 Apartments",
      Offices: "07 Offices",
      cover: "./images/location/city-6.png",
    },
  ]